### ISSUE TITLE
Small Icon for all contributors

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#103]
### *Added from Confluence "Idea-List"*

**Is your feature request related to a problem? Please describe.**
It is not visible for phonebook users who is contributing to the project. The idea is that everyone who contributes to the project gets a small icon or batch. 
-> This can have many positive effects. E.g. more people will contribute to the project because it is noticeable for others that you had contributed.

**Describe the solution you'd like**
A small icon or batch next to the user image.  It's also possible to make different icon colors for the number of contributions or something like that.

**Additional context**
I am not sure if it's possible to release this feature without a mark in the backend. We can write the contributor names in a file and if the name of a user is in this file the icon will be added on load. But before that fwe need to ask for permission of the contributor because the file will be in the public repository.

**Comment by mschwrdtnr** [comment]
We discussed about and don't want to implement this. Should we close this issue @DanielHabenicht ?

**Comment by DanielHabenicht** [comment]
Yep thats fine we implemented a better idea with #189
