### ISSUE TITLE
Page does not load in Safari

### ISSUE THREAD

**Issue by stefanbethke** [T-Systems-MMS/phonebook#114]
**Describe the bug:**
When opening the Phonebook in Safari 12.1.2 on macOS 10.14.6, the page does not load. The following error message is logged to the console:

```
ReferenceError: Can't find variable: ENV
```

This corresponds to this source code line:
```
            ravenURL: "${RAVEN_URL}" !== ENV.ravenURL ? ENV.ravenURL : null,
```

**To Reproduce:**
1. Go to the Phonebook URL in Safari.

**Expected behavior:**
The page should load.

**Comment by DanielHabenicht** [comment]
Can you have a look at the index.html? Maybe on the [demo page](http://demo-phonebook.me). There should be a script tag in the `<head>` which defines the `ENV` variable. 

I don't have a mac so it's a little bit tricky to debug.

**Comment by stefanbethke** [comment]
I see that the ENV variable is set in the header (verified with the debugger). However, inside the module, it doesn't appear to be available.

I see `<script src="runtime..." type="module">` It appears that modules don't have access to the main context and it's global variables, at least in Safari. I believe that this is the intended behaviour with ES6 modules.

**Comment by DanielHabenicht** [comment]
Apparently, this did not solve the problem :/

**Comment by stefanbethke** [comment]
If I set `window.ENV=ENV` in the debugger just after the script block on the page, it works.
