### ISSUE TITLE
Links in dark theme are not readable

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#119]
**To Reproduce:**
Profilbild > Einstellungen > Farbschema: Blau-Dunkel Farbschema
Beobachtung:
Links auf sind dunkelblau auf dunkelgrauem Hintergrund. Das ist sehr schwer lesbar.

**Expected behavior:**

Bei dem Farbschema sind Links als selbige zu erkennen und gut lesbar.

**Screenshots:**

![image](https://user-images.githubusercontent.com/13590797/62036315-ddec5b00-b1f1-11e9-8b90-b6e981f493fc.png)

**Additional Context**
Internal Issue: 8728

**Comment by mschwrdtnr** [comment]
I think this is also a problem with `magenta-dark-theme`.

![image](https://user-images.githubusercontent.com/39745446/62525433-b02d9480-b837-11e9-941d-4d0c3eb3afee.png)
