### ISSUE TITLE
Information is incorrect - Button

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#174]
**Is your feature request related to a problem? Please describe.**
It's a common problem that the data of users are not correct. This could be: different room, phone number etc.

**Describe the solution you'd like**
A small button on the users information page which opens an info-dialog. The dialog should contain information how to change personal details with the internal ticket tool. An example is provided on the telekom-phonebook.

**Describe alternatives you've considered**
It would be cool if the user can see an example in the dialog.

**Additional context**
It's possible that many people request changes and flood the BT.

**Comment by DanielHabenicht** [comment]
Maybe something more general? 

Like `Changing your data in the phonebook is not possible but you can change it here: <Link>. Just create a general Ticket demanding the change of your data.`

**Comment by DanielHabenicht** [comment]
Reopen this? @mschwrdtnr 
If you want to have the reversion in production you still have to bump the version number.

**Comment by mschwrdtnr** [comment]
Until we don't have a new release and don't update the production we don't need to do this, right? I think that we just wait for the next release and use this version number. Or is this not possible?

**Comment by DanielHabenicht** [comment]
That is sufficient.

**Comment by DanielHabenicht** [comment]
1. Open a new PR for the implementation.
2. Update the credentials for the preview together with @paule96. So you can preview the changes. 
3. Fix the position of the Button and when it is displayed.

**Comment by mschwrdtnr** [comment]
> That is sufficient. You might want to add a label like "ready" or "in work" in order to signal if something can get merged.

That would be another new label. But i think about a possibility to automate something like that.

**Comment by Zeroks77** [comment]
@DanielHabenicht  whutface Oo

What should I change where and how?
Please give me some clues what you dont like
