### ISSUE TITLE
Release notes only show up sometimes

### ISSUE THREAD

**Issue by marcuskrahl** [T-Systems-MMS/phonebook#178]
**Describe the bug:**
When trying to access the release notes via the menu bar, the modal for release notes is only opening in about every third try. The other times nothing happens after clicking the button.

**To Reproduce:**

1. Open Phonebook
2. Click user icon in top right corner
3. Click on release notes
4. If the release notes modal is shown, try again

**Expected behavior:**
The release notes modal is shown every time

**Screenshots:**
![phonebook_release_notes](https://user-images.githubusercontent.com/527426/63243467-e79a3900-c25a-11e9-8586-3926ab064c81.gif)

**Additional context:**
Reproducable in Firefox ESR and latest Chrome

**Comment by DanielHabenicht** [comment]
Any console output?

Cheers
Daniel

________________________________

**Comment by marcuskrahl** [comment]
No console output. If you click at the very far left and right of the button the modal is never shown. However it also seems that if you click in the middle of the button it sometimes also does not show the modal (like in the gif)

**Comment by DanielHabenicht** [comment]
https://github.com/T-Systems-MMS/phonebook/blob/1d7fb3a4ddd56dd3c01b39d678a2889d7282636d/Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html#L173

Seems that the click action is attached to the wrong element

**Comment by mschwrdtnr** [comment]
my bad. Fix -> #180
