### ISSUE TITLE
[docs] add a link to azure devops

### ISSUE THREAD

**Issue by GentleJames** [T-Systems-MMS/phonebook#193]
Hi, im new to the Project and i wonder where the builds are running? Cant find a link to azure devops in the documentation.

**Comment by mschwrdtnr** [comment]
Would be cool, but i am not sure if we are allowed to do this. What do you say @DanielHabenicht ?

**Comment by paule96** [comment]
yes we are allowed. Because that is linked currently in the PRs (but microsoft has a problem so the links are broken...)

**Comment by mschwrdtnr** [comment]
Okay. Maybe you, @DanielHabenicht or @GentleJames wants to provide a page for the documentation with some explanations abotu Azure DevOps and so on?

**Comment by paule96** [comment]
yes it is assign to me ;)

**Comment by mschwrdtnr** [comment]
resolves in #200
