### ISSUE TITLE
Make Feature Request more prominent and easier

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#194]
![image](https://user-images.githubusercontent.com/13590797/63753289-0fb91600-c8b3-11e9-8e0d-283a272cbadf.png)
Aus dem Bild geht nicht hervor das hier auch Ideen gemeldet werden können, dies sollte also sprachlich ergänzt werden, in der Art:

"Bug melden oder Idee einreichen"

Weiterhin wird bei dem danach öffnenden Dialog nur Github oder der Link der privaten Organisation angeboten, hier sollte für technisch nicht so versierte Nutzer auch der Weg einer Mail angeboten werden (gleich wie auf der Info Seite). 
![image](https://user-images.githubusercontent.com/13590797/63753448-632b6400-c8b3-11e9-9d9b-6236eac5058f.png)

**Comment by mschwrdtnr** [comment]
**Interview result:** Rename "Report a Bug" to "Make a wish".

**Comment by mschwrdtnr** [comment]
- [ ] Link: Contact your organization via Email (`contactEmail` variable in `runtime-environment.ts`)
- [ ] Link: Contact your organization repository (`contactUrl` variable in `runtime-environment.ts`) 
What would be a good naming for this @DanielHabenicht ?
- [ ] Link: [Report a Bug](https://github.com/T-Systems-MMS/phonebook/issues/new?assignees=&labels=bug&template=bug_report.md)
- [ ] Link: [Make a wish](https://github.com/T-Systems-MMS/phonebook/issues/new?assignees=&labels=feature&template=feature_request.md) (or something like)
- [ ] Cancel

**Comment by FrankLambrette** [comment]
@mschwrdtnr @Zeroks77 any idea how to fit the width of the mat-menu-panel to the inner content?

![image](https://user-images.githubusercontent.com/55480780/68114448-4f752d00-fef6-11e9-9b00-af0363e5f4a1.png)

**Comment by mschwrdtnr** [comment]
@FrankLambrette I would prefer to use a line break. Otherwise the menu is very big only because of one item.

**Comment by FrankLambrette** [comment]
> @FrankLambrette I would prefer to use a line break. Otherwise the menu is very big only because of one item.
> I think a span for "Melde einen Bug oder" and span for "teile eine neue Idee" in this button will be the best solution.

@mschwrdtnr this would be a bit hacky i guess: [new line in mat-menu-item](https://stackoverflow.com/questions/54022588/how-to-show-full-text-and-wrap-in-menu-item-in-angular-material)

**Comment by mschwrdtnr** [comment]
Okay, maybe we should change the text to "Submit Feedback". For me this declarative enough. Or what do you think?

**Comment by DanielHabenicht** [comment]
How about two buttons? 
Share your thoughts
And
Report a bug

**Comment by mschwrdtnr** [comment]
@DanielHabenicht think that this can be a bit overloaded and probably not useful because the person will redirect to the `feedbackdrawersheet`.
