### ISSUE TITLE
Feature und Enhancement zusammenlegen

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#195]
Es gibt nur noch features, dies sollte auch in den Templates reflektiert werden.

**Comment by mschwrdtnr** [comment]
I would just change "about" in [feature_request](https://github.com/T-Systems-MMS/phonebook/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) to "Suggest an idea or enhancement for this project" and delete the enhancement template. Or what do you think @DanielHabenicht ?

**Comment by DanielHabenicht** [comment]
passt, wenn es sonst keine unterschiede gibt.
