### ISSUE TITLE
List contributors on welcome-page

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#204]
It would be cool if all contributors will be listed on the welcome-page (`display-notification.dialog`).

It's only necessary to adapt the function in `page-information`.

Example in `page-information`
![image](https://user-images.githubusercontent.com/39745446/63862615-25ab0180-c9ad-11e9-81b4-7e49e3933456.png)

**Comment by DanielHabenicht** [comment]
You can reuse the code by making a component/module out of this card

**Comment by paule96** [comment]
will this fixed by #202?

**Comment by mschwrdtnr** [comment]
Nope. #202 will only list the contributors on the information-page.
