### ISSUE TITLE
Fix number of shown contributors in table

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#221]
The table for all contributors insert a line break after 7 persons. The line break is only necessary for the md-Files. It doesn't look good in the application.

![image](https://user-images.githubusercontent.com/39745446/64441264-d318c600-d0cd-11e9-8011-7bb9a287a032.png)

**Comment by mschwrdtnr** [comment]
Maybe use `display: inline-flex;`

**Comment by DanielHabenicht** [comment]
A Bug that is not in master is not a bug! Fix it in the PR ;)
