### ISSUE TITLE
add Per-repository settings for line-endings

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#261]
Maybe we should add a `.gitattributes`-File. So everyone have the same line endings and don't need to change them in their personal gitconfig. What do you think @DanielHabenicht ?

https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by mschwrdtnr** [comment]
or maybe it's enough to write it into the documentation.

**Comment by DanielHabenicht** [comment]
https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by mschwrdtnr** [comment]
@DanielHabenicht ???
So add a .gitattributes?
