### ISSUE TITLE
Small picture in the navbar instead of person-icon

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#278]
![image](https://user-images.githubusercontent.com/39745446/64859828-9bf56800-d62b-11e9-9dcc-285eb948f666.png)

**Comment by BrunoZirnstein** [comment]
i would like to add the image

**Comment by mschwrdtnr** [comment]
@Zeroks77 ...

**Comment by mschwrdtnr** [comment]
resolved in #376
