### ISSUE TITLE
searching for rooms by number

### ISSUE THREAD

**Issue by acordts** [T-Systems-MMS/phonebook#297]
If rooms are defined it makes sense to be able to search for them as well.

**Comment by mschwrdtnr** [comment]
Hey @acordts, it is already possible to search for rooms.
The two ways are:
- Type in a room number (can also show other things)
- Type "Room: 123" to set the room as a filter.

**Be sure that your Room-Column is displayed. It is only possible to search for displayed columns.**
To activate the room-column take a look at the below screenshot.
![image](https://user-images.githubusercontent.com/39745446/65044391-193b1880-d95d-11e9-8b1f-979977420fc7.png)

**Comment by mschwrdtnr** [comment]
Hey @acordts, i tested it again and it looks like the second way isn't working in the english version.
