### ISSUE TITLE
docs: add old contributors

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#316]
@all-contributors please add @renkin for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @schurzi for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @renkin for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @oliverguhr for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @danielsy for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @renkin for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @danielsy for code, ideas

**Comment by mschwrdtnr** [comment]
@all-contributors please add @oliverguhr for code, ideas

**Comment by DanielHabenicht** [comment]
@mschwrdtnr good to close?

**Comment by mschwrdtnr** [comment]
I thought i should include other contributors but apparently not^^
