### ISSUE TITLE
Show Post Code for Location on user-profile

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#324]
**Is your feature request related to a problem? Please describe.**
If someone needs to send a package to another location they have to google the postal code because they don't see it on the user page.

**Describe the solution you'd like**
Write the postal code next to the city.

**Comment by BrunoZirnstein** [comment]
i would like to add this

**Comment by mschwrdtnr** [comment]
Cool. Thank you @BrunoZirnstein!
