### ISSUE TITLE
Place a link to the user-guide

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#349]
Find a good way and place to link to the user guide.
A good place could be:
- Welcome Dialog
- Information-Page
- ...

_If the issue will be solved by an internal employee it would cool if he also makes a blogpost about the user-guide and how to access to him!_

**Comment by BrunoZirnstein** [comment]
Ich würde den Issue übernehmen.

**Comment by mschwrdtnr** [comment]
@BrunoZirnstein great! 🎉 
I think that a link on the information-page is enough. But i also don't know what the best solution and presentation of this link could be. Maybe you can make a new mat-card with information about the user-guide and a small description of the feature #328

**Comment by DanielHabenicht** [comment]
Why the link to #328?
