### ISSUE TITLE
Location missing

### ISSUE THREAD

**Issue by Zeroks77** [T-Systems-MMS/phonebook#394]
![image](https://user-images.githubusercontent.com/40673554/67670529-60f98a80-f974-11e9-8477-015de862bb9c.png)

![image](https://user-images.githubusercontent.com/40673554/67670547-68209880-f974-11e9-9f45-c134434a7965.png)

Some locations are missing the pictures from google maps

**Comment by DanielHabenicht** [comment]
That's likely an internal issue. Please have a look at the data provided by the backend. There should be no link to google maps so none is displayed.

**Comment by Zeroks77** [comment]
but when there is a given location in the Phonebook i would normaly expect that all behave the same ... so either remove the Locations without or add it

**Comment by DanielHabenicht** [comment]
Yep, but that is an internal issue and has nothing to do with the application, just as you won't raise a bug if the user information are incorrect.

**Comment by mschwrdtnr** [comment]
@Zeroks77 you can open an internal issue. I will close this for now.
