### ISSUE TITLE
Export to Excel/CSV

### ISSUE THREAD

**Issue by SecMyth** [T-Systems-MMS/phonebook#415]
I'd really like an export functionality to either Excel or CSV.
Based on the search filter the resulting list shouldbe able to be exported into a download file.

**Comment by mschwrdtnr** [comment]
Hey @SecMyth thanks for you Issue 🎉 

Unfortunately we are not allowed to implement this feature because of company compliance. If you still have questions feel free to contact us under phonebook-t-systems-mms@mg.telekom.de
