### ISSUE TITLE
Unit-Tests and E2E Tests are failing

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#416]
Unit-Tests and E2E Tests are failing:

@DanielHabenicht: "The Chrome Webdriver and the installed Chrome version do not match. That's why there is no connection.
The solution is probably to install the matching version of chromedriver before running the test. But for E2E that's not really important as we don't really have any tests running there. But Unit tests are pretty important, so fix them first."

- Karma-tests and ngn-tests should match

@DanielHabenicht: _The basic problem of webdriver version and chrome version being out sync is gone._

**Comment by DanielHabenicht** [comment]
The e2e tests are working again. Now only the unit tests are failing because one test fails (by timing out). If somebody can test out which test is failing everything will be green again. @mschwrdtnr

**Comment by DanielHabenicht** [comment]
The basic problem of webdriver version and chrome version being out sync is gone.

**Comment by mschwrdtnr** [comment]
> The e2e tests are working again. Now only the unit tests are failing because one test fails (by timing out). If somebody can test out which test is failing everything will be green again. @mschwrdtnr

How should this be done? How can i test which test is failing?

**Comment by DanielHabenicht** [comment]
Trial and error, uncomment half of the them try again, test if it is still failing, try again until you have the test failing.

**Comment by mschwrdtnr** [comment]
Mhhh but if i test it with jasmin all tests are passing.. sometimes there is the timeout error in the console but this is also a bit random and not every time.

**Comment by DanielHabenicht** [comment]
I know it is a tedious process but I could not find another solution.

**Comment by mschwrdtnr** [comment]
But i still don't get it.. how can i test it if i don't get an error message with test:dev-chrome?^^

**Comment by DanielHabenicht** [comment]
The Error is within search.state.spec.ts the test. Looks like it runs into an infinite loop

**Comment by DanielHabenicht** [comment]
Ok so this was an issue coming from @ngxs/router-plugin, that caused an infinite loop while deleting query parameters.
