### ISSUE TITLE
People in Dev Enviroment can't be found

### ISSUE THREAD

**Issue by Zeroks77** [T-Systems-MMS/phonebook#431]
When I tried to test my new implementations, I was confronted with this problem.
It seems that the backend mock is not working right now. 

![image](https://user-images.githubusercontent.com/40673554/69945109-2e99fa80-14e9-11ea-9039-52f051807676.png)

![image](https://user-images.githubusercontent.com/40673554/69945226-6c971e80-14e9-11ea-93e3-9075b80b9495.png)

**Comment by DanielHabenicht** [comment]
try yourself, the docker container must be running and reachable under the port give in this command:
https://github.com/T-Systems-MMS/phonebook/blob/e6c263789cbc85f447571657de78e5079c53b529/Phonebook.Frontend/package.json#L8

**Comment by DanielHabenicht** [comment]
try to give some more context and logs

**Comment by mschwrdtnr** [comment]
For me everything is working - Version 2.1.0.4

**Comment by Zeroks77** [comment]
🤷‍♂️ somethimes it works, somethimes it doesn't....

Don't know how to reproduce it

**Comment by DanielHabenicht** [comment]
Post the log if it happens again
