### ISSUE TITLE
🎄 Christmas Sprint 

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#432]
I would like to get all PRs through till Christmas. 

Please notify the colleagues that still have a PR open. 

This way we can do some heavy maintenance and structure of the project after Christmas (see #430)

**Comment by Zeroks77** [comment]
@T-Systems-MMS/phonebook-developers merry Christmas have great holidays and a happy new year

I am looking forward to work with you further guys.

**Comment by mschwrdtnr** [comment]
Sorry @danielhabenicht, i haven't the time and motivation to finish my pr. Can you tell us again what is need to be done or it is fine like that? I also don't lile the open prs, but... 🤷‍♂️

**Comment by DanielHabenicht** [comment]
No action is required, just that the PR might need some significant work after restructuring the project.

**Comment by DanielHabenicht** [comment]
so no worries and have great last Christmas day
