### ISSUE TITLE
Git Action for Labeling out PR's

### ISSUE THREAD

**Issue by Zeroks77** [T-Systems-MMS/phonebook#439]
Hey, guys,

since I read about Git actions, I have been looking for a nice way to use them because I think they are just a great addition to Github.

As I browsed through some of the actions on the marketplace, I found this action. 
https://github.com/marketplace/actions/condition-based-pull-request-labeler

This action identifies your PR's based on the configuration. 

What do you think about it?

**Comment by mschwrdtnr** [comment]
I also wanted to implement something like this. and would say... test the action in your forked repo and we can give you feedback how the config-file should look like.

It should be enough if the labels based on the pr-title. We can think about how the state "mergeable" could be help our workflow and if we add a new label for this.

Didn't found it right now, but it would be cool if this action is also triggered if the pr-title is changing while the pr is open (e.g. if the title is not like our conventions or smth like).

**Comment by DanielHabenicht** [comment]
Can you give some ideas on what you want to implement?
I don't really see a benefit for labels that correspond to the PR title. 
But I would be open to labels that correspond to the part of the application modified.

**Comment by Zeroks77** [comment]
But labeling corresponding with the title are much more beneficial in our case.

Let's say I implement an feature then the corresponding title would be something like this : feat(blub) :blab 

The action would label this pr as feature. 

So if you write an title with the right description you get the labels the pr need to have.

**Comment by Zeroks77** [comment]
I am currently testing on how the action works. The regex it uses is kinda confusing maybe I need to change the code a bit

**Comment by DanielHabenicht** [comment]
Yep but my problem with this is: the information about this or beeing a feature pr is already available because it is written in the title.

**Comment by mschwrdtnr** [comment]
For my opinion this action haven't a great use case and it's not that hard to label prs manual. But i thought that we sayd, that this project is also to test new stuff and new technologies. 
So if he implements it right and it have a benefit why don't let him do this action?

**Comment by DanielHabenicht** [comment]
> So if he implements it right and it have a benefit why don't let him do this action?

You are right. @Zeroks77 if you still want to implement it, go ahead.
