### ISSUE TITLE
Auto Table Columns

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#452]
**Is your feature request related to a problem? Please describe.**

On smaller screens, the information overlap and you can't really use it because it is too much
![image](https://user-images.githubusercontent.com/13590797/70666153-5d913880-1c6e-11ea-9f36-c78d413822b0.png)

**Describe the solution you'd like**

Automatically strip down the column count like this. 

![image](https://user-images.githubusercontent.com/13590797/70666393-d1334580-1c6e-11ea-95c4-6360658f1c0c.png)

This can also be made configurable just like the other table setting.

**Comment by friedaxvictoria** [comment]
@DanielHabenicht What exactly is a migration for? In what way would a use one in this issue?

**Comment by DanielHabenicht** [comment]
well just program your solution I will take a look then.
The goal is to migrate the data from existing users to the new state property (E.g. if you rename `visibleColumns` to `bigScreenVisibleColumns`)

**Comment by friedaxvictoria** [comment]
The general idea seems to be working well without a mirgration. I am simply using two different states. The only issue right now is that whenever I drag one column to the left/right it changes both states instead of only one. On reset everything is fine again...Do you have any idea what might solve this?

**Comment by DanielHabenicht** [comment]
Of course, it works without migration. Just that everybody who has setup custom table columns will lose them with the update, that's why we need to write a migration. 

Publish your branch and make a PR, then we can discuss on the code.
