### ISSUE TITLE
The frontend Builds are failing!

### ISSUE THREAD

**Issue by paule96** [T-Systems-MMS/phonebook#47]
The builds are currently not working. This blocks PRs.

@DanielHabenicht can you take a look in it?

**Comment by paule96** [comment]
can we use a headless chrome for our tests? So we don't depend on the build agent?

**Comment by DanielHabenicht** [comment]
We are already using chrome headless what you are proposing is using pupeteer.

**Comment by paule96** [comment]
This was fixed by #51
