### ISSUE TITLE
Blank screen using Internet Explorer

### ISSUE THREAD

**Issue by tomfrenzel** [T-Systems-MMS/phonebook#492]
**Describe the bug:**
The phonebook isn't loading when using IE, it just returns a blank screen. There are some errors in the Developer Console.

**Screenshots:**
![phonebook](https://user-images.githubusercontent.com/40773830/73527831-07da4080-4414-11ea-9510-57078bccf64a.png)

**Additional context:**
That Problem also appends to other People from my Company.

**Comment by mschwrdtnr** [comment]
Hey @tomfrenzel, this problem was already reported in #445 . But thanks anyway for your issue.
