### ISSUE TITLE
Update the docs in the frontend source code

### ISSUE THREAD

**Issue by paule96** [T-Systems-MMS/phonebook#5]
In the frontend source code, there is a docs folder with some information for developers to get started with this repo. But there are many missing pieces of information. 

So the goal of this issue is to remove all TODO's in the .md files under [docs](https://github.com/T-Systems-MMS/phonebook/tree/master/Phonebook.Frontend/docs).

**Comment by DanielHabenicht** [comment]
@paule96 Looks like this is resolved: https://github.com/T-Systems-MMS/phonebook/search?q=TODO&unscoped_q=TODO

**Comment by paule96** [comment]
yes this can be closed
