### ISSUE TITLE
April 2020 🦄

### ISSUE THREAD

**Issue by Zeroks77** [T-Systems-MMS/phonebook#505]
Warteschleife mit Einhorn bei jeder Anfrage auf der Seite.

"Das nächste freie Einhorn ist für sie reserviert."

Optional : 
1. Random Ladebalken der vor **und** zurück geht
   - wenn ladebalken zurück geht ist ein einhorn gestorben :C
1. Pink Fluffy Unicorn im Hintergrund laufen für die Ladezeit
1. Pink / Einhorn Theme

@mschwrdtnr  @DanielHabenicht  was meint ihr 

@paule96  hat ja gesagt

**Comment by DanielHabenicht** [comment]
Find ich gut, bis azf

**Comment by DanielHabenicht** [comment]
Find ich gut, bis azf

**Comment by mschwrdtnr** [comment]
sure, why not. As daniel said.. the usability should still be guaranteed.

I would say the Milestone and the label "prio-1" are wrong. But we still not have any guidelines..
