### ISSUE TITLE
Use github-bot for release, instead of my user account

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#52]
Use a GitHub bot account, e.g. "tsystemmsmms-bot" for adding release comments and creating releases.

**Comment by mschwrdtnr** [comment]
I am not sure but think that @jandd provided an account. Why are we not using the account @DanielHabenicht ?

**Comment by DanielHabenicht** [comment]
Still in the making, there are two pull requests still open
