### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by paule96** [T-Systems-MMS/phonebook#591]
> #### This is a public issue tracker. 
> #### Be sure that your description and screenshots not contain any personal or company info.

**Describe the bug:**

If you search numbers the search try to find only one result. Or something like this. I have the case if I type 3 numbers (xxx) the search result ist empty, I add one number (xxxx) my search result has for entries.

**To Reproduce:**

Maybe we can reproduce this with 3510. This number comes from the demo site. The number is given to two members in the demo environment. But if you type only 351 it's find nothing.

**Expected behavior:**

Find also the two people if I only type 3 numbers

**Screenshots:**
> **Please pay attention to not disclose personal information!**

**Additional context:**

**Comment by paule96** [comment]
cc @DanielHabenicht

**Comment by DanielHabenicht** [comment]
What property are you searching for? Telephone numbers?

**Comment by paule96** [comment]
Telephonnumber, rooms, mobile, etc..

Everything that can have a number

**Comment by DanielHabenicht** [comment]
Search for rooms should work. 

Telephone and mobile numbers are only working for more than 4 digits (by design)

**Comment by paule96** [comment]
bad design maybe? :) can we change this?

**Comment by DanielHabenicht** [comment]
No, Nobody searches for only 4 digits of a number. That's no real use case.

I agree that we should follow through with the room number.

**Comment by paule96** [comment]
Not an issue anymore.
