### ISSUE TITLE
No loading animation TableComponent

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#596]
The new backend is a little bit slow (more than >300ms). 

In this case, the user is confronted with: 
![image](https://user-images.githubusercontent.com/13590797/78711057-a902dd00-7916-11ea-8af8-eb578fc0dac4.png)

There should be a loading animation like 
https://material.angular.io/components/progress-spinner/overview

This fix is only for the tablecomponent. Not for other components (like rooms).

Furthermore:
 - In case there is an error (failing web request) there should be an error message, like `We couldn't retrieve the data from the backend. Please <button> contact us </button>`

**Comment by DanielHabenicht** [comment]
yep, just modify the function you are calling to generate the error. 

Display it where the table should be, as it is at the moment.

**Comment by DanielHabenicht** [comment]
Just another thing, we should separate errors, where there is no actual backend error. 

Like "We couldn't reach the data service. Are you connected to the internet?"

**Comment by friedaxvictoria** [comment]
@DanielHabenicht Could that even happen? If the user isn't connected to the internet, they wouldn't even be able to open the phonebook in the first place. Could there maybe be an issue with VPN that could cause the phonebook to work but the data doesn't get reached?
