### ISSUE TITLE
user: Automatically put focus on the search bar

### ISSUE THREAD

**Issue by laerling** [T-Systems-MMS/phonebook#6]
When opening the phonebook, the search bar is not initially focused.
I need to click into the search bar before being able to type a search query.

Steps to reproduce:
1. Open phonebook
2. Start typing
3. No text is entered in search bar

Does not work in Browsers:
 - FF 67.0.4

**Comment by mschwrdtnr** [comment]
Works just for Chrome at the moment.

**Comment by paule96** [comment]
> Works just for Chrome at the moment.

not true

**Comment by DanielHabenicht** [comment]
Seems to work in all major browsers (Edge, Chrome, Firefox) from version 1.38.0 onwards
