### ISSUE TITLE
bug(user): User-Image have problems with delete/change (chrome)

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#61]
**Describe the bug:**
If you want to change your user image or delete it the page won't show the change/delete. It also doesn't change if you restart the browser. 
*The problem only occur in Chrome!*

The picture gets deleted from the picture endpoint and you can see the result in other browsers (firefox, edge). 

**To Reproduce:**
1. Go to "My Profile"
2. Change/delete your Picture
3. Reload the page

**Expected behavior:**
I can change/delete my profile image and the result is, that is

**Additional context:**
This issue was listed intern as *BUG 8594*.

**Comment by DanielHabenicht** [comment]
this is the service worker behaving in the wrong way. 
Should be self-destructed (by resolving `ngsw.json` with a 404) and setup with the new angular 8 mode supporting both `/en` and `/de` subpages.
