### ISSUE TITLE
Search results overlaps the search bar

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#658]
**Describe the bug:**
Text of the search results overlaps the search bar on smaller devices.
![image](https://user-images.githubusercontent.com/39745446/80479957-23d87a00-8950-11ea-9505-dc9082b9b329.png)

The text is not readable on the white themes.
![image](https://user-images.githubusercontent.com/39745446/80479931-191de500-8950-11ea-8dce-7c93e81243da.png)

**To Reproduce:**
1. Open the phonebook
2. Downsize your screen
3. Search for someone
4. Take a look at the search results.

**Expected behavior:**
I can imagine, that the searchbar will give the text more space or the text is placed above the settings icon.

**Comment by friedaxvictoria** [comment]
Is there a certain size that is the minimum? So, under a certain size it doesn't matter what it looks like because nobody uses that size anyway.
