### ISSUE TITLE
demo domain will be canceled mid june

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#701]
The https://demo-phonebook.me domain will be ending on mid-June (June 19 2020) 

I won't renew the domain name. 
This effectively means there will be no demo environments anymore.

@T-Systems-MMS/phonebook-developers if somebody wants to fill the gap you are welcome.

**Comment by paule96** [comment]
But the demo will be still alive just under another domain?

**Comment by DanielHabenicht** [comment]
nope no domain. Just one IP for the master branch.

**Comment by mschwrdtnr** [comment]
We don't really need a domain, or what do you think? Do you know the traffic of the demo?

**Comment by DanielHabenicht** [comment]
Nope, just like I said the preview won't work anymore because it is based on the domain.

**Comment by DanielHabenicht** [comment]
Mhm, I just thought about it. I may let it live in the other domain I own... it just would not be phonebook in the main domain anymore. More like pr-12.phonebook.domain.de

**Comment by mschwrdtnr** [comment]
Do we really need a main domain? Why not just ".azurewebsite.net"?

**Comment by DanielHabenicht** [comment]
Because the pr previews need a wildcard domain and azure websites does not provided wildcard domains for Kubernetes
