### ISSUE TITLE
Color scheme doesn't get saved

### ISSUE THREAD

**Issue by sbke-mms** [T-Systems-MMS/phonebook#835]
**Describe the bug:**
When I change my color scheme it doesn't get saved permanently. I'm not sure if it resets after a longer amount of time or if it is just after every release of a new version.

**To Reproduce:**

1. Go to setting
2. Set a color scheme different than the default
3. Close the phonebook
4. Wait several weeks or until new release (not sure what the trigger is
5. Open phonebook
6. Phonebook is displayed in default color scheme

**Expected behavior:**

Phonebook is displayed in the previously set color scheme

**Comment by mschwrdtnr** [comment]
Hey @sbke-mms, thanks for your report! 
What Browser do you use? I had the same color scheme for months and my current theme lasts since first April.

**Comment by sbke-mms** [comment]
Hi @mschwrdtnr I use "Blau-Dunkel" but I also realized there haven't been updates in ages and I do get the update modal regularly. So I gotta assume it's a cookie that resets somewhere or something along those lines. I'm not sure if this is a phonebook related issue or maybe it's an issue in my browser (Firefox).

**Comment by paule96** [comment]
Yes if you use Firefox inside the MMS all cookies will be deleted. But phonebook needs them to function correctly

**Comment by mr-woodapple** [comment]
Closing this issue as this doesn't seem to be related to the Phonebook.
