### ISSUE TITLE
Start search when Enter is pressed without Text Change in Searchbar

### ISSUE THREAD

**Issue by JankKeks** [T-Systems-MMS/phonebook#9]
1. Share Search URL f.e. https://demo-phonebook.me/en/search/billy
2. Site opens, shows all employees, searchbar is filled
3. Enter is pressed - nothing happens - requested behavior: start search 
optional: at step 2 search is automatic started without enter.

**Comment by mschwrdtnr** [comment]
Hey @JankKeks, i think this issue is fixed, right?

**Comment by mschwrdtnr** [comment]
Works in Chrome, Firefox and Edge. Can we close this @T-Systems-MMS/phonebook-admins ?
