### ISSUE TITLE
bug(user): it's not possible to search for "München"

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#98]
**Describe the bug:**
It's not possible to search for words with _ü._ It's also not possible to replace the word with _ue_.

**To Reproduce:**
- Try to search for "München"
-> No results
- Try to search for "Muenchen"
-> No results
- ../search/?city=M%C3%BCnchen
-> also no results

**Expected behavior:**
It should be possible to filter for "München"

**Additional context:**
The search is working with names but not with citys.

**Comment by DanielHabenicht** [comment]
regression of #10. 
use the same solution as in #71 and it should be fined
