### ISSUE TITLE
Make Environment Variables for the Frontend App Optional

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#99]
Make Variables like 
 - `ROOMPLANNINGTOOL_URL`
 - `CONTACT_EMAIL`
 - `CONTACT_URL`
 - `RAVEN_URL` 

truly optional by removing them from the `.sh` script but also make the app deal with those variables if they are not supplied. 

Update the Documentation Accordingly.

**Comment by mschwrdtnr** [comment]
I think that can be closed @DanielHabenicht ?
https://github.com/T-Systems-MMS/phonebook/commit/86cb717430ee3c41b904359163cd52ff2454d526 should fixed it

**Comment by DanielHabenicht** [comment]
Its documented here: https://github.com/T-Systems-MMS/phonebook/tree/master/Phonebook
But its not up to date.

**Comment by DanielHabenicht** [comment]
so after syncing and linking it to the documentation page this can be closed.
